services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 10s
      retries: 5
    env_file: .env
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - DEVICE=${DEVICE}
    volumes:
      - venv_data:/app/.venv
      - ./models:/app/models:ro
      - ./.env:/app/.env:ro
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ./logging.ini:/app/logging.ini:ro
      - ./logs:/app/logs
    expose:
      - "8000"
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      web:
        condition: service_healthy
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  # .venv 전용 named volume
  venv_data: