version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no

  uvicorn.error:
    level: INFO
    handlers: [console, file]
    propagate: no

  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: no

  model_utils:
    level: INFO
    handlers: [console, file]
    propagate: no

  chat_ws:
    level: INFO
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file]